server:
  name: "project-user"
  addr: "127.0.0.1:8080"

zap:
  debugFileName: "C:\\Users\\Nap\\Desktop\\v1\\ms_project\\logs\\debug\\project-debug.log"
  infoFileName: "C:\\Users\\Nap\\Desktop\\v1\\ms_project\\logs\\info\\project-info.log"
  warnFileName: "C:\\Users\\Nap\\Desktop\\v1\\ms_project\\logs\\debug\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

grpc:
  name: "user"
  addr: "127.0.0.1:8881"
  version: "1.0.0"
  weight: 2

etcd:
  addrs:
    - "127.0.0.1:2379"
mysql:
  username: root
  password: root
  host: 127.0.0.1
  port: 3309
  db: msproject

jwt:
  accessExp: 7
  refreshExp: 14
  accessSecret: msproject
  refreshSecret: ms_project